# Generated by Django 5.0.6 on 2024-06-09 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0003_newquote_alter_quote_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newquote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quotesapp.author'),
        ),
    ]
