# Generated by Django 5.0.6 on 2024-06-09 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotesapp', '0004_alter_newquote_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewQuote',
        ),
    ]
